Asset-Management.Web/Controllers/RequestAssetController.cs
using Asset_Management.Repository;
using Asset_Management.Service;
using Asset_Management.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Asset_Management.Web.Controllers
{
    public class RequestAssetController : Controller
    {
        private readonly RequestAssetService _service;

        public RequestAssetController(ApplicationDbContext context)
        {
            _service = new RequestAssetService(context);
        }

        [HttpGet]
        public IActionResult Index()
        {
            var request = _service.GetRequestAssets();
            return View(request);
        }
        [HttpGet]
        public IActionResult Approve(long? id)
        {
            _service.ApproveRequest(id);
            return Redirect("/RequestAsset");
        }

        [HttpGet]
        public IActionResult Reject(long? id)
        {
            return View();
        }

        [HttpPost]
        public IActionResult SaveRejection([Bind("Id, Reason")] ApprovalReq req)
        {
            if (ModelState.IsValid)
            {
                _service.SaveRejection(req);
                return Redirect("Index");
            }
            return View("Reject", req);
        }
    }
}

Asset-Management.Web/Views/RequestAsset/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<Asset_Management.ViewModel.RequestAssetModel>
@{
    ViewBag.Title = "Request Asset";
    // Approval team
    Layout = "_Layout";
}
<h2>Request Asset</h2>

<table class="table table-responsive">
    <thead>
        <tr>
            <th>Id</th>
            <th>PIC Name</th>
            <th>PIC Address</th>
            <th>Specification</th>
            <th>Date</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.PicName</td>
                <td>@item.PicAddress</td>
                <td>@item.Specification</td>
                <td>@item.RequestDate</td>
                <td>
                    <a asp-action="Approve" asp-route-id="@item.Id" class="btn btn-sm btn-success" id="approved">Approve</a>
                    <a asp-action="Reject" asp-route-id="@item.Id" class="btn btn-sm btn-danger" id="rejected">Reject</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@*<div class="modal" tabindex="-1" id="approved-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Success</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Request has been Approved</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>*@

@section Scripts
{
    <script type="text/javascript">
        $(function () {
            $("#approved").click(function () {
                alert("Request has been approved")
                //$("#approved-modal").modal("show");
            });
        });
    </script>
}

Asset-Management.Web/Views/RequestAsset/Reject.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model Asset_Management.ViewModel.ApprovalReq

@{
    ViewBag.Title = "Rejection";
    Layout = "_Layout";
}

<h2>Form Rejection</h2>
<form asp-controller="RequestAsset" asp-action="SaveRejection" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Reason">Reason</label>
        <input asp-for="Reason" class="form-control" />
        <span asp-validation-for="Reason" class="text-danger"></span>
    </div>
    <input type="hidden" asp-for="RequestAssetId" />
    <input type="hidden" asp-for="Status" />
    <input type="hidden" asp-for="UpdatedDate" />

    <div class="pt-2 pb-2">
        <button type="submit" class="btn btn-sm btn-primary">Submit</button>
        <a asp-action="Index" class="btn btn-sm btn-success">Back</a>
    </div>
    
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}